### ISSUE TITLE
[Umbrella] Support the management of resources across additional dimensions

### ISSUE THREAD

**Issue by caohe** [kubewharf/katalyst-core#7]
#### Why is this needed?

Currently, Katalyst supports the management of CPU and memory resources, including the cgroups configuration during container creation and real-time adjustments during subsequent runtime.

To support more colocation scenarios, Katalyst needs to manage resources across a broader range of dimensions, including network, L3 cache, memory bandwidth, and more.

#### What would you like to be added?

- Proposals
  - [ ] add external manager proposal

- APIs
  - [ ] https://github.com/kubewharf/katalyst-api/issues/1
  - [ ] define the CRD for QoS related to RDT

- External Manager
  - [ ] https://github.com/kubewharf/katalyst-core/issues/4
  - [ ] https://github.com/kubewharf/katalyst-core/issues/6
  - [ ] implement a network external manager to enable the execution of packet tagging in cgroups v2 environments

- QRM Plugins
  - [ ] https://github.com/kubewharf/katalyst-core/issues/5
  - [ ] extend the CPU QRM plugin to support diverse RDT-related management policies
